version: "3.7"

services:
  sistem_penjualan_skripsi_app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: sistem_penjualan_skripsi_app
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - sistem_penjualan_skripsi_db
    restart: always
    networks:
      - app-network

  sistem_penjualan_skripsi_db:
    image: mariadb:lts-jammy
    container_name: sistem_penjualan_skripsi_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - sistem_penjualan_skripsi_db:/var/lib/mysql/
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistem_penjualan_skripsi_phpmyadmin
    restart: always
    ports:
      - 8013:80
    environment:
      PMA_HOST: sistem_penjualan_skripsi_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin
    depends_on:
      - sistem_penjualan_skripsi_db
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    ports:
      - 8012:80
      - 8443:443
    restart: on-failure
    networks:
      - app-network  # Make sure Nginx is on the same network

networks:
  app-network:
    driver: bridge

volumes:
  sistem_penjualan_skripsi_db:
    driver: local
